const PAGES = [{
	"name": "100a",
	"image": "cover_small.png",
	"group": "architecture",
	"title": "Title",
	"description": "hello"
}, {
	"name": "11a",
	"image": "altcover_small.jpg",
	"group": "architecture",
	"title": "Title",
	"description": "hello"
}, {
	"name": "11b",
	"image": "axon_small.jpg",
	"group": "architecture",
	"title": "Title",
	"description": "hello"
}, {
	"name": "delsol",
	"image": "cover_small.jpg",
	"group": "architecture",
	"title": "Title",
	"description": "hello"
}, {
	"name": "brb",
	"image": "cover_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "dimsum",
	"image": "HarGao_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "election",
	"image": "cover_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "gryffin",
	"image": "cover_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "pameranposkad",
	"image": "cover_small.jpg",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "rocknroller",
	"image": "jennychen_rocknrollerlogo1_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "ssashirt",
	"image": "ssashirt_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "urbansketching",
	"image": "cover_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "warp",
	"image": "cover_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "summer",
	"image": "jenny_personalproject_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "turkey",
	"image": "turkey1_small.jpeg",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "celebration",
	"image": "cover_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}, {
	"name": "change",
	"image": "cover_small.png",
	"group": "illustrations",
	"title": "Title",
	"description": "hello"
}];